---
version: "3.8"

services:

  redis:
    image: redis:alpine
    deploy:
      resources:
        limits:
          memory: "512M"
        reservations:
          memory: "256M"

  mysql:
    image: mysql:5.7
    container_name: mysql
    volumes:
      - ./mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "munboard"
      MYSQL_USER: "munboard"
      MYSQL_PASSWORD: "munboard"
    ports:
      - "13309:3306"
    restart: always

  nginx:
    hostname: nginx
    ports:
      - "8080:80"
    image: "bit3/nginx-waf:latest"
    restart: always    
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "1"
          memory: "128M"
    # ignored for docker swarm
    depends_on:
      - php
    volumes:
      - type: bind
        source: "/home/kdavies/projects/Muns-Image-Board/src"
        target: "/var/www/default/htdocs/httpdocs/"
      - type: bind
        source: "/home/kdavies/projects/Muns-Image-Board/docker-configs/site.conf"
        target: "/etc/nginx/conf.d/default.conf"
      - type: bind
        source: "/home/kdavies/projects/Muns-Image-Board/docker-configs/nginx.conf"
        target: "/etc/nginx/nginx.conf"

  php:
    hostname: php
    environment:
      NEW_GID: 1000
      NEW_UID: 1000
      TIMEZONE: Europe/London
    image: "devilbox/php-fpm:8.2-prod"
    restart: always
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "1"
          memory: "512M"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    # ignored for docker swarm
    volumes:
      - type: bind
        source: "/home/kdavies/projects/Muns-Image-Board/src"
        target: "/var/www/default/htdocs/httpdocs/"
      - type: bind
        source: "/home/kdavies/projects/Muns-Image-Board/docker-configs/custom-php"
        target: "/etc/php-custom.d"
