---
version: "3.8"

services:
  redis:
    image: redis:alpine
    restart: always
    volumes:
      - ${sitePath}/redis-data:/data
    deploy:
      resources:
        limits:
          memory: "512M"
        reservations:
          memory: "256M"

  mysql:
    image: mysql:8
    env_file:
      - "${sitePath}/.env"
    volumes:
      - ${sitePath}/mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "munboard"
      MYSQL_USER: "munboard"
      MYSQL_PASSWORD: "munboard"
    ports:
      - "13309:3306"
    restart: always

  nginx:
    hostname: nginx
    ports:
      - "8080:80"
    image: "bit3/nginx-waf:latest"
    restart: always
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "2"
          memory: "1024M" # Set to larger value if you need to support larger file uploads
    # ignored for docker swarm
    depends_on:
      - php
    volumes:
      - type: bind
        source: "${sitePath}/src"
        target: "/var/www/default/htdocs/httpdocs/"
      - type: bind
        source: "${sitePath}/docker-configs/site.conf"
        target: "/etc/nginx/conf.d/default.conf"
      - type: bind
        source: "${sitePath}/docker-configs/nginx.conf"
        target: "/etc/nginx/nginx.conf"

  php:
    hostname: php
    env_file:
      - "${sitePath}/.env"
    environment:
      NEW_GID: 1000
      NEW_UID: 1000
      TIMEZONE: Europe/London
    image: "devilbox/php-fpm:8.2-prod"
    restart: always
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: "4"
          memory: "2048M"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    # ignored for docker swarm
    volumes:
      - type: bind
        source: "${sitePath}/src"
        target: "/var/www/default/htdocs/httpdocs/"
      - type: bind
        source: "${sitePath}/docker-configs/custom-php"
        target: "/etc/php-custom.d"

# phpdoc/phpdoc
  # phpdoc:
  #   image: phpdoc/phpdoc
  #   volumes:
  #     - ${sitePath}/src:/data
  #   ports:
  #     - "8083:80"
